"""Fixed ForeignKey relationship between Ticket and Department

Revision ID: 8e8a525f5f7f
Revises: bef1d2cfa66d
Create Date: 2025-02-22 03:19:13.927547
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8a525f5f7f'
down_revision = 'bef1d2cfa66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        # Adding a name for the foreign key constraint
        batch_op.create_foreign_key('fk_ticket_department', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        # Drop the constraint using the specified name
        batch_op.drop_constraint('fk_ticket_department', type_='foreignkey')

    # ### end Alembic commands ###
